import '../styles/editor.scss';
import './formats/dynamic-site-info';
import './formats/dynamic-placeholder';
import './plugins/single-template-panel';
import './plugins/post-display-meta-panel';
import './plugins/core-image-fancybox-toggle';
// import './plugins/custom-classname-textarea';
import './styles/button-decormos';
import './styles/group-section';
import './styles/heading-style-1';
import './styles/list-long-dash';
import './styles/list-toc';
import './styles/paragraph-style-1';
import './styles/table-decormos';
