import '../styles/editor.scss';
import './formats/dynamic-site-info';
import './formats/dynamic-placeholder';
import './plugins/single-template-panel';
import './styles/button-decormos';
import './styles/group-section';
import './styles/list-long-dash';
import './styles/list-toc';
import './styles/table-decormos';
